
var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var g=Object.assign({},moduleArg),aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da=Object.assign({},g),ea="./this.program",fa=(a,b)=>{throw b;},m="",ha,ia;m=self.location.href;_scriptName&&(m=_scriptName);m.startsWith("blob:")?m="":m=m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+1);ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};
ha=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ja=g.print||console.log.bind(console),r=g.printErr||console.error.bind(console);Object.assign(g,da);da=null;g.thisProgram&&(ea=g.thisProgram);g.quit&&(fa=g.quit);var ka;g.wasmBinary&&(ka=g.wasmBinary);var la,u=!1,ma,v,w,oa,pa,x,y,qa,ra,sa,ta;
function ua(){var a=la.buffer;g.HEAP8=v=new Int8Array(a);g.HEAP16=oa=new Int16Array(a);g.HEAPU8=w=new Uint8Array(a);g.HEAPU16=pa=new Uint16Array(a);g.HEAP32=x=new Int32Array(a);g.HEAPU32=y=new Uint32Array(a);g.HEAPF32=qa=new Float32Array(a);g.HEAPF64=ta=new Float64Array(a);g.HEAP64=ra=new BigInt64Array(a);g.HEAPU64=sa=new BigUint64Array(a)}var va=[],wa=[],xa=[];function ya(){var a=g.preRun.shift();va.unshift(a)}var A=0,za=null,Aa=null;function Ba(){A++;g.monitorRunDependencies?.(A)}
function Ca(){A--;g.monitorRunDependencies?.(A);if(0==A&&(null!==za&&(clearInterval(za),za=null),Aa)){var a=Aa;Aa=null;a()}}function D(a){g.onAbort?.(a);a="Aborted("+a+")";r(a);u=!0;ma=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Da=a=>a.startsWith("data:application/octet-stream;base64,"),Ea;function Fa(a){if(a==Ea&&ka)return new Uint8Array(ka);if(ia)return ia(a);throw"both async and sync fetching of the wasm failed";}
function Ga(a){return ka||"function"!=typeof fetch?Promise.resolve().then(()=>Fa(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Fa(a))}function Ha(a,b,c){return Ga(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{r(`failed to asynchronously prepare wasm: ${d}`);D(d)})}
function Ia(a,b){var c=Ea;return ka||"function"!=typeof WebAssembly.instantiateStreaming||Da(c)||"function"!=typeof fetch?Ha(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){r(`wasm streaming compile failed: ${e}`);r("falling back to ArrayBuffer instantiation");return Ha(c,a,b)}))}var Ja={55856:(a,b,c,d)=>{globalThis.results.push([a?E(w,a):"",b,c,d])}};
function Ka(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var La=a=>{for(;0<a.length;)a.shift()(g)},Ma=g.noExitRuntime||!0;class Na{constructor(a){this.Y=a-24}Gb(a,b){y[this.Y+16>>2]=0;y[this.Y+4>>2]=a;y[this.Y+8>>2]=b}}
var Oa=0,Pa=0,Qa=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Ra,G=a=>{for(var b="";w[a];)b+=Ra[w[a++]];return b},H={},I={},Sa={},J,Ta=a=>{throw new J(a);},Ua,Va=(a,b,c)=>{function d(l){l=c(l);if(l.length!==a.length)throw new Ua("Mismatched type converter count");for(var q=0;q<a.length;++q)L(a[q],l[q])}a.forEach(function(l){Sa[l]=b});var e=Array(b.length),f=[],k=0;b.forEach((l,q)=>{I.hasOwnProperty(l)?e[q]=I[l]:(f.push(l),H.hasOwnProperty(l)||
(H[l]=[]),H[l].push(()=>{e[q]=I[l];++k;k===f.length&&d(e)}))});0===f.length&&d(e)};function Wa(a,b,c={}){var d=b.name;if(!a)throw new J(`type "${d}" must have a positive integer typeid pointer`);if(I.hasOwnProperty(a)){if(c.rc)return;throw new J(`Cannot register type '${d}' twice`);}I[a]=b;delete Sa[a];H.hasOwnProperty(a)&&(b=H[a],delete H[a],b.forEach(e=>e()))}
function L(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return Wa(a,b,c)}
var Xa=(a,b,c)=>{switch(b){case 1:return c?d=>v[d]:d=>w[d];case 2:return c?d=>oa[d>>1]:d=>pa[d>>1];case 4:return c?d=>x[d>>2]:d=>y[d>>2];case 8:return c?d=>ra[d>>3]:d=>sa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ya=a=>{throw new J(a.S.lb.kb.name+" instance already deleted");},Za=!1,$a=()=>{},bb=(a,b,c)=>{if(b===c)return a;if(void 0===c.nb)return null;a=bb(a,b,c.nb);return null===a?null:c.mc(a)},cb={},db=[],eb=()=>{for(;db.length;){var a=db.pop();a.S.Ab=!1;a["delete"]()}},
fb,gb={},hb=(a,b)=>{if(void 0===b)throw new J("ptr should not be undefined");for(;a.nb;)b=a.Db(b),a=a.nb;return gb[b]},jb=(a,b)=>{if(!b.lb||!b.Y)throw new Ua("makeClassHandle requires ptr and ptrType");if(!!b.ob!==!!b.mb)throw new Ua("Both smartPtrType and smartPtr must be specified");b.count={value:1};return ib(Object.create(a,{S:{value:b,writable:!0}}))},ib=a=>{if("undefined"===typeof FinalizationRegistry)return ib=b=>b,a;Za=new FinalizationRegistry(b=>{b=b.S;--b.count.value;0===b.count.value&&
(b.mb?b.ob.vb(b.mb):b.lb.kb.vb(b.Y))});ib=b=>{var c=b.S;c.mb&&Za.register(b,{S:c},b);return b};$a=b=>{Za.unregister(b)};return ib(a)};function kb(){}
var lb=(a,b)=>Object.defineProperty(b,"name",{value:a}),mb=(a,b,c)=>{if(void 0===a[b].sb){var d=a[b];a[b]=function(...e){if(!a[b].sb.hasOwnProperty(e.length))throw new J(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].sb})!`);return a[b].sb[e.length].apply(this,e)};a[b].sb=[];a[b].sb[d.Eb]=d}},nb=(a,b)=>{if(g.hasOwnProperty(a))throw new J(`Cannot register public name '${a}' twice`);g[a]=b},ob=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,
"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function pb(a,b,c,d,e,f,k,l){this.name=a;this.constructor=b;this.Bb=c;this.vb=d;this.nb=e;this.pc=f;this.Db=k;this.mc=l;this.xc=[]}var qb=(a,b,c)=>{for(;b!==c;){if(!b.Db)throw new J(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.Db(a);b=b.nb}return a};
function rb(a,b){if(null===b){if(this.Qb)throw new J(`null is not a valid ${this.name}`);return 0}if(!b.S)throw new J(`Cannot pass "${Qa(b)}" as a ${this.name}`);if(!b.S.Y)throw new J(`Cannot pass deleted object as a pointer of type ${this.name}`);return qb(b.S.Y,b.S.lb.kb,this.kb)}
function sb(a,b){if(null===b){if(this.Qb)throw new J(`null is not a valid ${this.name}`);if(this.Ib){var c=this.yc();null!==a&&a.push(this.vb,c);return c}return 0}if(!b||!b.S)throw new J(`Cannot pass "${Qa(b)}" as a ${this.name}`);if(!b.S.Y)throw new J(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Hb&&b.S.lb.Hb)throw new J(`Cannot convert argument of type ${b.S.ob?b.S.ob.name:b.S.lb.name} to parameter type ${this.name}`);c=qb(b.S.Y,b.S.lb.kb,this.kb);if(this.Ib){if(void 0===
b.S.mb)throw new J("Passing raw pointer to smart pointer is illegal");switch(this.Ac){case 0:if(b.S.ob===this)c=b.S.mb;else throw new J(`Cannot convert argument of type ${b.S.ob?b.S.ob.name:b.S.lb.name} to parameter type ${this.name}`);break;case 1:c=b.S.mb;break;case 2:if(b.S.ob===this)c=b.S.mb;else{var d=b.clone();c=this.zc(c,tb(()=>d["delete"]()));null!==a&&a.push(this.vb,c)}break;default:throw new J("Unsupporting sharing policy");}}return c}
function ub(a,b){if(null===b){if(this.Qb)throw new J(`null is not a valid ${this.name}`);return 0}if(!b.S)throw new J(`Cannot pass "${Qa(b)}" as a ${this.name}`);if(!b.S.Y)throw new J(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.S.lb.Hb)throw new J(`Cannot convert argument of type ${b.S.lb.name} to parameter type ${this.name}`);return qb(b.S.Y,b.S.lb.kb,this.kb)}function vb(a){return this.fromWireType(y[a>>2])}
function wb(a,b,c,d,e,f,k,l,q,p,n){this.name=a;this.kb=b;this.Qb=c;this.Hb=d;this.Ib=e;this.wc=f;this.Ac=k;this.cc=l;this.yc=q;this.zc=p;this.vb=n;e||void 0!==b.nb?this.toWireType=sb:(this.toWireType=d?rb:ub,this.pb=null)}
var xb=(a,b)=>{if(!g.hasOwnProperty(a))throw new Ua("Replacing nonexistent public symbol");g[a]=b;g[a].Eb=void 0},yb=(a,b,c=[])=>{a=a.replace(/p/g,"i");return(0,g["dynCall_"+a])(b,...c)},zb=(a,b)=>(...c)=>yb(a,b,c),M=(a,b)=>{a=G(a);var c=zb(a,b);if("function"!=typeof c)throw new J(`unknown function pointer with signature ${a}: ${b}`);return c},Ab,Cb=a=>{a=Bb(a);var b=G(a);N(a);return b},Db=(a,b)=>{function c(f){e[f]||I[f]||(Sa[f]?Sa[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Ab(`${a}: `+
d.map(Cb).join([", "]));},Eb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(y[b+4*d>>2]);return c},Fb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Gb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].pb)return!0;return!1}
function Hb(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=lb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}var Ib=a=>{try{a()}catch(b){D(b)}},Jb=a=>{if(!u)try{if(a(),!Ma)try{ma=ma=a=ma,Ma||(g.onExit?.(a),u=!0),fa(a,new Ka(a))}catch(b){b instanceof Ka||"unwind"==b||fa(1,b)}}catch(b){b instanceof Ka||"unwind"==b||fa(1,b)}};
function Kb(){var a=O,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...e)=>{P.Fb.push(c);try{return d(...e)}finally{u||(P.Fb.pop(),P.tb&&P.state===P.wb.Vb&&0===P.Fb.length&&(P.state=P.wb.Mb,Ib(Lb),"undefined"!=typeof Fibers&&Fibers.zd()))}}:d;return b}function Mb(){var a=Q(12+P.Ub),b=a+12,c=P.Ub;y[a>>2]=b;y[a+4>>2]=b+c;b=P.Fb[0];c=P.Yb[b];void 0===c&&(c=P.ec++,P.Yb[b]=c,P.Xb[c]=b);x[a+8>>2]=c;return a}
function Nb(a){if(!u){if(P.state===P.wb.Mb){var b=!1,c=!1;a((d=0)=>{if(!u&&(P.ac=d,b=!0,c)){P.state=P.wb.Tb;Ib(()=>Ob(P.tb));"undefined"!=typeof Browser&&Browser.Rb.oc&&Browser.Rb.resume();d=!1;try{var e=(0,O[P.Xb[x[P.tb+8>>2]]])()}catch(l){e=l,d=!0}var f=!1;if(!P.tb){var k=P.Nb;k&&(P.Nb=null,(d?k.reject:k.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(P.state=P.wb.Vb,P.tb=Mb(),"undefined"!=typeof Browser&&Browser.Rb.oc&&Browser.Rb.pause(),Ib(()=>Pb(P.tb)))}else P.state===P.wb.Tb?(P.state=P.wb.Mb,
Ib(Qb),N(P.tb),P.tb=null,P.Bc.forEach(Jb)):D(`invalid state: ${P.state}`);return P.ac}}var P={bd(a){var b=/^(invoke_.*|__asyncjs__.*)$/;for(let [c,d]of Object.entries(a))"function"==typeof d&&(d.cd||b.test(c))},wb:{Mb:0,Vb:1,Tb:2,Jc:3},state:0,Ub:4096,tb:null,ac:0,Fb:[],Yb:{},Xb:{},ec:0,Nb:null,Bc:[],Cd(){return new Promise((a,b)=>{P.Nb={resolve:a,reject:b}})},$c(a){return Nb(b=>{a().then(b)})}};
function Rb(a,b,c,d,e,f){var k=b.length;if(2>k)throw new J("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&null!==c,q=Gb(b);c="void"!==b[0].name;d=[a,Ta,d,e,Fb,b[0],b[1]];for(e=0;e<k-2;++e)d.push(b[e+2]);d.push(P);if(!q)for(e=l?1:2;e<b.length;++e)null!==b[e].pb&&d.push(b[e].pb);q=Gb(b);var p=b.length,n=e="";for(k=0;k<p-2;++k)e+=(0!==k?", ":"")+"arg"+k,n+=(0!==k?", ":"")+"arg"+k+"Wired";e=`\n        return function (${e}) {\n        if (arguments.length !== ${p-
2}) {\n          throwBindingError('function ' + humanName + ' called with ' + arguments.length + ' arguments, expected ${p-2}');\n        }`;q&&(e+="var destructors = [];\n");var B=q?"destructors":"null",C="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");l&&(e+="var thisWired = classParam['toWireType']("+B+", this);\n");for(k=0;k<p-2;++k)e+="var arg"+k+"Wired = argType"+k+"['toWireType']("+B+", arg"+k+");\n",C.push("argType"+k);l&&(n="thisWired"+(0<n.length?", ":
"")+n);e+=(c||f?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";f=c?"rv":"";C.push("Asyncify");e+=`function onDone(${f}) {\n`;if(q)e+="runDestructors(destructors);\n";else for(k=l?1:2;k<b.length;++k)l=1===k?"thisWired":"arg"+(k-2)+"Wired",null!==b[k].pb&&(e+=`${l}_dtor(${l});\n`,C.push(`${l}_dtor`));c&&(e+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [h,t]=[C,e+"}\n"+`return Asyncify.currData ? Asyncify.whenDone().then(onDone) : onDone(${f});\n`+"}\n"];h.push(t);b=Hb(h)(...d);
return lb(a,b)}
var Sb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Tb=[],R=[],tb=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Tb.pop()||R.length;R[b]=a;R[b+1]=1;return b}},Ub={name:"emscripten::val",fromWireType:a=>{if(!a)throw new J("Cannot use deleted val. handle = "+a);var b=R[a];9<a&&0===--R[a+1]&&(R[a]=void 0,Tb.push(a));return b},toWireType:(a,b)=>tb(b),argPackAdvance:8,readValueFromPointer:vb,pb:null},Vb=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(qa[c>>
2])};case 8:return function(c){return this.fromWireType(ta[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},S=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var l=a.charCodeAt(++f);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=
128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e},T=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Wb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,E=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Wb)return Wb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|
f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Xb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Yb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&pa[c];)++c;c<<=1;if(32<c-a&&Xb)return Xb.decode(w.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=oa[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Zb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;
var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)oa[b>>1]=a.charCodeAt(e),b+=2;oa[b>>1]=0;return b-d},$b=a=>2*a.length,ac=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=x[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},bc=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}x[b>>2]=
f;b+=4;if(b+4>c)break}x[b>>2]=0;return b-d},cc=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},dc=a=>0===a%4&&(0!==a%100||0===a%400),ec=[0,31,60,91,121,152,182,213,244,274,305,335],fc=[0,31,59,90,120,151,181,212,243,273,304,334],gc=[],U=[],hc=!1,ic=[];function jc(a,b){var c=Array(T(a)+1);a=S(a,c,0,c.length);b&&(c.length=a);return c}
var kc=[],lc={},nc=()=>{if(!mc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in lc)void 0===lc[b]?delete a[b]:a[b]=lc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);mc=c}return mc},mc,oc=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);D("initRandomDevice")},pc=
a=>(pc=oc())(a),qc=[31,29,31,30,31,30,31,31,30,31,30,31],rc=[31,28,31,30,31,30,31,31,30,31,30,31],sc=(a,b,c,d)=>{function e(h,t,z){for(h="number"==typeof h?h.toString():h||"";h.length<t;)h=z[0]+h;return h}function f(h,t){return e(h,t,"0")}function k(h,t){function z(Z){return 0>Z?-1:0<Z?1:0}var F;0===(F=z(h.getFullYear()-t.getFullYear()))&&0===(F=z(h.getMonth()-t.getMonth()))&&(F=z(h.getDate()-t.getDate()));return F}function l(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;
case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function q(h){var t=h.yb;for(h=new Date((new Date(h.zb+1900,0,1)).getTime());0<t;){var z=h.getMonth(),F=(dc(h.getFullYear())?qc:rc)[z];if(t>F-h.getDate())t-=F-h.getDate()+1,h.setDate(1),11>z?h.setMonth(z+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+1));else{h.setDate(h.getDate()+
t);break}}z=new Date(h.getFullYear()+1,0,4);t=l(new Date(h.getFullYear(),0,4));z=l(z);return 0>=k(t,h)?0>=k(z,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var p=y[d+40>>2];d={Ec:x[d>>2],Dc:x[d+4>>2],Jb:x[d+8>>2],Sb:x[d+12>>2],Kb:x[d+16>>2],zb:x[d+20>>2],qb:x[d+24>>2],yb:x[d+28>>2],yd:x[d+32>>2],Cc:x[d+36>>2],Fc:p?p?E(w,p):"":""};c=c?E(w,c):"";p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S",
"%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in p)c=c.replace(new RegExp(n,"g"),p[n]);var B="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),C="January February March April May June July August September October November December".split(" ");p={"%a":h=>B[h.qb].substring(0,3),"%A":h=>B[h.qb],"%b":h=>
C[h.Kb].substring(0,3),"%B":h=>C[h.Kb],"%C":h=>f((h.zb+1900)/100|0,2),"%d":h=>f(h.Sb,2),"%e":h=>e(h.Sb,2," "),"%g":h=>q(h).toString().substring(2),"%G":q,"%H":h=>f(h.Jb,2),"%I":h=>{h=h.Jb;0==h?h=12:12<h&&(h-=12);return f(h,2)},"%j":h=>{for(var t=0,z=0;z<=h.Kb-1;t+=(dc(h.zb+1900)?qc:rc)[z++]);return f(h.Sb+t,3)},"%m":h=>f(h.Kb+1,2),"%M":h=>f(h.Dc,2),"%n":()=>"\n","%p":h=>0<=h.Jb&&12>h.Jb?"AM":"PM","%S":h=>f(h.Ec,2),"%t":()=>"\t","%u":h=>h.qb||7,"%U":h=>f(Math.floor((h.yb+7-h.qb)/7),2),"%V":h=>{var t=
Math.floor((h.yb+7-(h.qb+6)%7)/7);2>=(h.qb+371-h.yb-2)%7&&t++;if(t)53==t&&(z=(h.qb+371-h.yb)%7,4==z||3==z&&dc(h.zb)||(t=1));else{t=52;var z=(h.qb+7-h.yb-1)%7;(4==z||5==z&&dc(h.zb%400-1))&&t++}return f(t,2)},"%w":h=>h.qb,"%W":h=>f(Math.floor((h.yb+7-(h.qb+6)%7)/7),2),"%y":h=>(h.zb+1900).toString().substring(2),"%Y":h=>h.zb+1900,"%z":h=>{h=h.Cc;var t=0<=h;h=Math.abs(h)/60;return(t?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":h=>h.Fc,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(n in p)c.includes(n)&&
(c=c.replace(new RegExp(n,"g"),p[n](d)));c=c.replace(/\0\0/g,"%");n=jc(c,!1);if(n.length>b)return 0;v.set(n,a);return n.length-1},tc=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},uc=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=tc(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},V=a=>{var b=T(a)+1,c=vc(b);S(a,w,c,b);return c},W=
a=>{var b=wc();a=a();xc(b);return a},yc=a=>y[a>>2]+4294967296*x[a+4>>2],Ac=(a,b,c)=>X.handleError(W(()=>{var d=V(a);return zc(d,b,c)})),Bc=(a,b=438)=>Ac(a,b&4095|32768,0),Dc=(a,b)=>{var c=wc();a=V(a);if("string"==typeof b){var d=new Uint8Array(T(b)+1);b=S(b,d,0,d.length);b=d.slice(0,b)}d=Q(b.length);for(var e=0;e<b.length;e++)v[d+e]=b[e];b=Cc(a,d,b.length);N(d);xc(c);return b},Fc=(a,b,c,d,e)=>{a=b?a+"/"+b:a;d=Ec(d,e);hc?(Bc(a,d),Dc(a,c)):U.push({vc:a,$b:c,mode:d})},Gc=(a,b,c)=>{var d=`al ${a}`;ha(a,
e=>{b(new Uint8Array(e));d&&Ca(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Ba(d)},Hc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:X.lc();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=tc(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Jc=g.preloadPlugins||[],Kc=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.Gb();var e=!1;Jc.forEach(f=>{!e&&f.canHandle(b)&&
(f.handle(a,b,c,d),e=!0)});return e},Lc=(a,b,c,d,e,f,k,l,q)=>{function p(C){function h(t){q?.();l||Fc(a,b,t,d,e);f?.();Ca(B)}Kc(C,n,h,()=>{k?.();Ca(B)})||h(C)}var n=b?Hc(uc(a+"/"+b)):a,B=`cp ${n}`;Ba(B);"string"==typeof c?Gc(c,p,k):p(c)},Ec=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Nc=(a,b=511)=>X.handleError(W(()=>{var c=V(a);return Mc(c,b)})),Pc=a=>W(()=>{var b=V(a);return Oc(b)}),Y={},Qc={},Rc={};
function Sc(){X.rb||(X.rb=function(a){this.Pb=a;this.message="FS error";this.name="ErrnoError"},X.rb.prototype=Error(),X.rb.prototype.constructor=X.rb)}function Tc(a){var b=W(()=>Uc(V(a)));return 44==b?null:{ed:31==b,dd:!1}}function Vc(a){var b=a+88;return{Vc:y[a>>2],mode:y[a+4>>2],rd:y[a+8>>2],uid:y[a+12>>2],Zc:y[a+16>>2],sd:y[a+20>>2],size:yc(a+24),Oc:y[a+32>>2],Pc:y[a+36>>2],Nc:yc(a+40),pd:yc(a+56),Uc:yc(a+72),ad:y[b>>2]+4294967296*y[b+4>>2]}}
function Wc(a,b){var c=Xc(),d={Hc:b.read,Ic:b.write,dc:e=>{Rc[e]={}},nc:e=>{Rc[e]=void 0},getSize:()=>{},read:(e,f,k,l)=>{var q=g.Lb.subarray(f,f+k);try{var p=d.Hc(Rc[e],q,0,k,l)}catch(n){return-n.Pb}g.Lb.set(q,f);return p},write:(e,f,k,l)=>{var q=g.Lb.subarray(f,f+k);try{var p=d.Ic(Rc[e],q,0,k,l)}catch(n){return-n.Pb}g.Lb.set(q,f);return p}};Y[c]=d;Qc[a]=c}
function Yc(a,b,c){"undefined"===typeof c&&(c=b,b=438);var d=Qc[c];if(!d)throw Error("Invalid device ID.");return X.handleError(W(()=>Zc(V(a),b,d)))}
for(var X={Gb(){Sc()},rb:null,handleError(a){if(0>a)throw new X.rb(-a);return a},ic(a,b,c,d,e){Fc(a,b,c,d,e)},jc(a,b){for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=uc(a+"/"+c);hc?X.tc(d):gc.push({uc:a,fc:c});a=d}}return d},kc(a,b,c,d,e,f,k,l,q,p){return Lc(a,b,c,d,e,f,k,l,p)},lc:()=>{var a=$c();return a?E(w,a):""},Mc(a){var b=!!Tc(a);if(b){var c=c||"binary";if("utf8"!==c&&"binary"!==c)throw Error('Invalid encoding type "'+c+'"');var d=wc();a=ad(V(a));xc(d);d=new Uint8Array(w.subarray(a+
8,a+8+yc(a)));"utf8"===c&&(d=E(d,0));c=d}else c=null;return{Wc:b,object:{Sc:c}}},tc:(a,b)=>Nc(a,b),kd:(a,b)=>{a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{Nc(c,b)}catch(e){if(20!=e.Pb)throw e;}}},wd:a=>X.handleError(W(()=>bd(V(a)))),open:(a,b,c)=>W(()=>{if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);}else d=b;b=d;c="undefined"==typeof c?438:c;d=V(a);return{ub:X.handleError(cd(d,
b,c))}}),create:(a,b)=>Bc(a,b),close:a=>X.handleError(-dd(a.ub)),Gc:a=>Pc(a),Qc:a=>W(()=>{var b=V(a);return ed(b)}),read(a,b,c,d,e){var f="undefined"!=typeof e,k=Q(d);a=f?fd(a.ub,k,d,e):gd(a.ub,k,d);a=X.handleError(a);for(e=0;e<d;e++)b[c+e]=v[k+e];N(k);return a},write(a,b,c,d,e){for(var f="undefined"!=typeof e,k=Q(d),l=0;l<d;l++)v[k+l]=b[c+l];a=f?hd(a.ub,k,d,e):jd(a.ub,k,d);a=X.handleError(a);N(k);return a},Kc(a,b,c){return X.handleError(kd(a.ub,BigInt(b),BigInt(c)))},Dd:(a,b)=>Dc(a,b),md:(a,b,c,
d,e)=>({Y:X.handleError(ld(b,d,e,a.ub,BigInt(c))),Lc:!0}),od:(a,b,c,d,e)=>{0===c||D();return X.handleError(md(b,d,e))},qd:(a,b)=>X.handleError(nd(a,b)),xd:(a,b)=>W(()=>od(V(a),V(b))),ud(a){var b=X.handleError(W(()=>pd(V(a))));return b?E(w,b):""},stat(a){var b=Q(96);X.handleError(W(()=>qd(V(a),b)));var c=Vc(b);N(b);return c},jd(a){var b=Q(96);X.handleError(W(()=>rd(V(a),b)));var c=Vc(b);N(b);return c},Rc(a,b){return X.handleError(W(()=>{var c=V(a);return sd(c,b)}))},gd(a,b){return X.handleError(W(()=>
{var c=V(a);return td(c,b)}))},Xc(a,b){return X.handleError(ud(a,b))},Bd:(a,b,c)=>X.handleError(W(()=>vd(V(a),b,c))),truncate(a,b){return X.handleError(W(()=>wd(V(a),BigInt(b))))},Yc(a,b){return X.handleError(xd(a,BigInt(b)))},td:a=>W(()=>{var b=V(a),c=[];b=yd(b);if(!b)throw Error("No such directory");for(var d;d=zd(b);)c.push(d?E(w,d):"");Ad(b);return c}),nd:(a,b,c)=>{var d=a.Tc(b);return X.handleError(W(()=>Bd(V(c),d)))},Ad:a=>X.handleError(W(()=>Cd(V(a)))),ld:(a,b,c)=>Ac(a,b,c),sc:(a,b)=>a<<8|
b,Ob(a,b,c,d){if("string"!=typeof a)throw Error("Only string paths are accepted");a=uc(a+"/"+b);b=Ec(!!c,!!d);X.Ob.bc||(X.Ob.bc=64);var e=X.sc(X.Ob.bc++,0);Wc(e,{read(f,k,l,q){for(var p=f=0;p<q;p++){try{var n=c()}catch(B){throw new X.rb(29);}if(void 0===n&&0===f)throw new X.rb(6);if(null===n||void 0===n)break;f++;k[l+p]=n}return f},write(f,k,l,q){for(f=0;f<q;f++)try{d(k[l+f])}catch(p){throw new X.rb(29);}return f}});return Yc(a,b,e)},vd(a,b){return X.handleError(W(()=>{var c=V(a),d=V(b);return Dd(c,
d)}))},hd(a,b,c){return X.handleError(Ed(a.ub,BigInt(b),c))}},Fd=Array(256),Gd=0;256>Gd;++Gd)Fd[Gd]=String.fromCharCode(Gd);Ra=Fd;J=g.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};Ua=g.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};
Object.assign(kb.prototype,{isAliasOf:function(a){if(!(this instanceof kb&&a instanceof kb))return!1;var b=this.S.lb.kb,c=this.S.Y;a.S=a.S;var d=a.S.lb.kb;for(a=a.S.Y;b.nb;)c=b.Db(c),b=b.nb;for(;d.nb;)a=d.Db(a),d=d.nb;return b===d&&c===a},clone:function(){this.S.Y||Ya(this);if(this.S.Cb)return this.S.count.value+=1,this;var a=ib,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.S;a=a(c.call(b,d,{S:{value:{count:e.count,Ab:e.Ab,Cb:e.Cb,Y:e.Y,lb:e.lb,mb:e.mb,ob:e.ob}}}));a.S.count.value+=1;a.S.Ab=
!1;return a},["delete"](){this.S.Y||Ya(this);if(this.S.Ab&&!this.S.Cb)throw new J("Object already scheduled for deletion");$a(this);var a=this.S;--a.count.value;0===a.count.value&&(a.mb?a.ob.vb(a.mb):a.lb.kb.vb(a.Y));this.S.Cb||(this.S.mb=void 0,this.S.Y=void 0)},isDeleted:function(){return!this.S.Y},deleteLater:function(){this.S.Y||Ya(this);if(this.S.Ab&&!this.S.Cb)throw new J("Object already scheduled for deletion");db.push(this);1===db.length&&fb&&fb(eb);this.S.Ab=!0;return this}});
g.getInheritedInstanceCount=()=>Object.keys(gb).length;g.getLiveInheritedInstances=()=>{var a=[],b;for(b in gb)gb.hasOwnProperty(b)&&a.push(gb[b]);return a};g.flushPendingDeletes=eb;g.setDelayFunction=a=>{fb=a;db.length&&fb&&fb(eb)};
Object.assign(wb.prototype,{qc(a){this.cc&&(a=this.cc(a));return a},Zb(a){this.vb?.(a)},argPackAdvance:8,readValueFromPointer:vb,fromWireType:function(a){function b(){return this.Ib?jb(this.kb.Bb,{lb:this.wc,Y:c,ob:this,mb:a}):jb(this.kb.Bb,{lb:this,Y:a})}var c=this.qc(a);if(!c)return this.Zb(a),null;var d=hb(this.kb,c);if(void 0!==d){if(0===d.S.count.value)return d.S.Y=c,d.S.mb=a,d.clone();d=d.clone();this.Zb(a);return d}d=this.kb.pc(c);d=cb[d];if(!d)return b.call(this);d=this.Hb?d.hc:d.pointerType;
var e=bb(c,this.kb,d.kb);return null===e?b.call(this):this.Ib?jb(d.kb.Bb,{lb:d,Y:e,ob:this,mb:a}):jb(d.kb.Bb,{lb:d,Y:e})}});Ab=g.UnboundTypeError=((a,b)=>{var c=lb(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
R.push(0,1,void 0,1,null,1,!0,1,!1,1);g.count_emval_handles=()=>R.length/2-5-Tb.length;X.Gb();
var Hd={a:(a,b,c)=>{(new Na(a)).Gb(b,c);Oa=a;Pa++;throw Oa;},F:()=>{D("")},k:(a,b,c)=>{b=G(b);L(a,{name:b,fromWireType:d=>d,toWireType:function(d,e){if("bigint"!=typeof e&&"number"!=typeof e)throw new TypeError(`Cannot convert "${Qa(e)}" to ${this.name}`);"number"==typeof e&&(e=BigInt(e));return e},argPackAdvance:8,readValueFromPointer:Xa(b,c,-1==b.indexOf("u")),pb:null})},m:(a,b,c,d)=>{b=G(b);L(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},argPackAdvance:8,
readValueFromPointer:function(e){return this.fromWireType(w[e])},pb:null})},O:(a,b,c,d,e,f,k,l,q,p,n,B,C)=>{n=G(n);f=M(e,f);l&&=M(k,l);p&&=M(q,p);C=M(B,C);var h=ob(n);nb(h,function(){Db(`Cannot construct ${n} due to unbound types`,[d])});Va([a,b,c],d?[d]:[],t=>{t=t[0];if(d){var z=t.kb;var F=z.Bb}else F=kb.prototype;t=lb(n,function(...ab){if(Object.getPrototypeOf(this)!==Z)throw new J("Use 'new' to construct "+n);if(void 0===K.xb)throw new J(n+" has no accessible constructor");var Ic=K.xb[ab.length];
if(void 0===Ic)throw new J(`Tried to invoke ctor of ${n} with invalid number of parameters (${ab.length}) - expected (${Object.keys(K.xb).toString()}) parameters instead!`);return Ic.apply(this,ab)});var Z=Object.create(F,{constructor:{value:t}});t.prototype=Z;var K=new pb(n,t,Z,C,z,f,l,p);if(K.nb){var na;(na=K.nb).Wb??(na.Wb=[]);K.nb.Wb.push(K)}z=new wb(n,K,!0,!1,!1);na=new wb(n+"*",K,!1,!1,!1);F=new wb(n+" const*",K,!1,!0,!1);cb[a]={pointerType:na,hc:F};xb(h,t);return[z,na,F]})},N:(a,b,c,d,e,f)=>
{var k=Eb(b,c);e=M(d,e);Va([],[a],l=>{l=l[0];var q=`constructor ${l.name}`;void 0===l.kb.xb&&(l.kb.xb=[]);if(void 0!==l.kb.xb[b-1])throw new J(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${l.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);l.kb.xb[b-1]=()=>{Db(`Cannot construct ${l.name} due to unbound types`,k)};Va([],k,p=>{p.splice(1,0,null);l.kb.xb[b-1]=Rb(q,p,null,e,f);return[]});return[]})},
g:(a,b,c,d,e,f,k,l,q)=>{var p=Eb(c,d);b=G(b);b=Sb(b);f=M(e,f);Va([],[a],n=>{function B(){Db(`Cannot call ${C} due to unbound types`,p)}n=n[0];var C=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&n.kb.xc.push(b);var h=n.kb.Bb,t=h[b];void 0===t||void 0===t.sb&&t.className!==n.name&&t.Eb===c-2?(B.Eb=c-2,B.className=n.name,h[b]=B):(mb(h,b,C),h[b].sb[c-2]=B);Va([],p,z=>{z=Rb(C,z,n,f,k,q);void 0===h[b].sb?(z.Eb=c-2,h[b]=z):h[b].sb[c-2]=z;return[]});return[]})},l:a=>L(a,Ub),j:(a,b,c)=>
{b=G(b);L(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:Vb(b,c),pb:null})},d:(a,b,c,d,e)=>{b=G(b);-1===e&&(e=4294967295);e=l=>l;if(0===d){var f=32-8*c;e=l=>l<<f>>>f}var k=b.includes("unsigned")?function(l,q){return q>>>0}:function(l,q){return q};L(a,{name:b,fromWireType:e,toWireType:k,argPackAdvance:8,readValueFromPointer:Xa(b,c,0!==d),pb:null})},c:(a,b,c)=>{function d(f){return new e(v.buffer,y[f+4>>2],y[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,
Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=G(c);L(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{rc:!0})},h:(a,b)=>{b=G(b);var c="std::string"===b;L(a,{name:b,fromWireType:function(d){var e=y[d>>2],f=d+4;if(c)for(var k=f,l=0;l<=e;++l){var q=f+l;if(l==e||0==w[q]){k=k?E(w,k,q-k):"";if(void 0===p)var p=k;else p+=String.fromCharCode(0),p+=k;k=q+1}}else{p=Array(e);for(l=0;l<e;++l)p[l]=String.fromCharCode(w[f+l]);p=p.join("")}N(d);return p},toWireType:function(d,
e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new J("Cannot pass non-string to std::string");var k=c&&f?T(e):e.length;var l=Q(4+k+1),q=l+4;y[l>>2]=k;if(c&&f)S(e,w,q,k+1);else if(f)for(f=0;f<k;++f){var p=e.charCodeAt(f);if(255<p)throw N(q),new J("String has UTF-16 code units that do not fit in 8 bits");w[q+f]=p}else for(f=0;f<k;++f)w[q+f]=e[f];null!==d&&d.push(N,l);return l},
argPackAdvance:8,readValueFromPointer:vb,pb(d){N(d)}})},f:(a,b,c)=>{c=G(c);if(2===b){var d=Yb;var e=Zb;var f=$b;var k=l=>pa[l>>1]}else 4===b&&(d=ac,e=bc,f=cc,k=l=>y[l>>2]);L(a,{name:c,fromWireType:l=>{for(var q=y[l>>2],p,n=l+4,B=0;B<=q;++B){var C=l+4+B*b;if(B==q||0==k(C))n=d(n,C-n),void 0===p?p=n:(p+=String.fromCharCode(0),p+=n),n=C+b}N(l);return p},toWireType:(l,q)=>{if("string"!=typeof q)throw new J(`Cannot pass non-string to C++ string type ${c}`);var p=f(q),n=Q(4+p+b);y[n>>2]=p/b;e(q,n+4,p+b);
null!==l&&l.push(N,n);return n},argPackAdvance:8,readValueFromPointer:vb,pb(l){N(l)}})},n:(a,b)=>{b=G(b);L(a,{fd:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},I:()=>1,J:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);x[b>>2]=a.getUTCSeconds();x[b+4>>2]=a.getUTCMinutes();x[b+8>>2]=a.getUTCHours();x[b+12>>2]=a.getUTCDate();x[b+16>>2]=a.getUTCMonth();x[b+20>>2]=a.getUTCFullYear()-1900;x[b+24>>2]=a.getUTCDay();x[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),
0,1,0,0,0,0))/864E5|0},K:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);x[b>>2]=a.getSeconds();x[b+4>>2]=a.getMinutes();x[b+8>>2]=a.getHours();x[b+12>>2]=a.getDate();x[b+16>>2]=a.getMonth();x[b+20>>2]=a.getFullYear()-1900;x[b+24>>2]=a.getDay();x[b+28>>2]=(dc(a.getFullYear())?ec:fc)[a.getMonth()]+a.getDate()-1|0;x[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
x[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},H:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=new Date(e,0,1),k=new Date(e,6,1);e=f.getTimezoneOffset();var l=k.getTimezoneOffset();y[a>>2]=60*Math.max(e,l);x[b>>2]=Number(e!=l);a=q=>q.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];f=a(f);k=a(k);l<e?(S(f,w,c,17),S(k,w,d,17)):(S(f,w,d,17),S(k,w,c,17))},z:(a,b)=>w.set(U[a].$b,b),w:()=>gc.length,x:()=>{hc=!0;return U.length},u:(a,b)=>{a=gc[a].fc;S(a,w,b,T(a)+1)},s:a=>
U[a].mode,A:a=>U[a].$b.length,v:(a,b)=>{a=gc[a].uc;S(a,w,b,T(a)+1)},t:(a,b)=>{a=U[a].vc;S(a,w,b,T(a)+1)},r:(a,b)=>Y[a].dc(b),i:(a,b)=>Y[a].nc(b),q:(a,b)=>Y[a].getSize(b),p:function(a,b,c,d,e){e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);return Y[a].read?Y[a].read(b,c,d,e):-28},o:function(a,b,c,d,e){e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);return Y[a].write?Y[a].write(b,c,d,e):-28},D:()=>{a:{if(!ic.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?
(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}ic=jc(a,!0)}a=ic.shift()}return"number"===typeof a?a:-1},y:(a,b,c)=>{kc.length=0;for(var d;d=w[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;kc.push(112==d?y[c>>2]:106==d?ra[c>>3]:105==d?x[c>>2]:ta[c>>3]);c+=e?8:4}return Ja[a](...kc)},b:()=>Date.now(),e:a=>r(a?E(w,a):""),C:a=>ja(a?E(w,a):""),G:a=>{var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=
b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-la.buffer.byteLength+65535)/65536;try{la.grow(e);ua();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},L:(a,b)=>{var c=0;nc().forEach((d,e)=>{var f=b+c;e=y[a+4*e>>2]=f;for(f=0;f<d.length;++f)v[e++]=d.charCodeAt(f);v[e]=0;c+=d.length+1});return 0},M:(a,b)=>{var c=nc();y[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);y[b>>2]=d;return 0},B:(a,b)=>{pc(w.subarray(a,a+b));
return 0},E:(a,b,c,d)=>sc(a,b,c,d)},O=function(){function a(c){O=c.exports;O=Kb();la=O.P;ua();wa.unshift(O.Q);Ca("wasm-instantiate");return O}var b={a:Hd};Ba("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){r(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}Ea||=g.locateFile?Da("zstd-js.wasm")?"zstd-js.wasm":g.locateFile?g.locateFile("zstd-js.wasm",m):m+"zstd-js.wasm":(new URL("zstd-js.wasm",import.meta.url)).href;Ia(b,function(c){a(c.instance)}).catch(ba);
return{}}(),Bb=a=>(Bb=O.R)(a),Q=g._malloc=a=>(Q=g._malloc=O.T)(a),N=g._free=a=>(N=g._free=O.U)(a),xc=a=>(xc=O.V)(a),vc=a=>(vc=O.W)(a),wc=()=>(wc=O.X)(),ad=a=>(ad=O.Z)(a),Cc=(a,b,c)=>(Cc=O._)(a,b,c),Mc=(a,b)=>(Mc=O.$)(a,b),bd=a=>(bd=O.aa)(a),cd=(a,b,c)=>(cd=O.ba)(a,b,c),kd=(a,b,c)=>(kd=O.ca)(a,b,c),zc=(a,b,c)=>(zc=O.da)(a,b,c),Oc=a=>(Oc=O.ea)(a),ed=a=>(ed=O.fa)(a),od=(a,b)=>(od=O.ga)(a,b),pd=a=>(pd=O.ha)(a),jd=(a,b,c)=>(jd=O.ia)(a,b,c),hd=(a,b,c,d)=>(hd=O.ja)(a,b,c,d),sd=(a,b)=>(sd=O.ka)(a,b),ud=(a,
b)=>(ud=O.la)(a,b),td=(a,b)=>(td=O.ma)(a,b),Ed=(a,b,c)=>(Ed=O.na)(a,b,c),Dd=(a,b)=>(Dd=O.oa)(a,b),gd=(a,b,c)=>(gd=O.pa)(a,b,c),fd=(a,b,c,d)=>(fd=O.qa)(a,b,c,d),wd=(a,b)=>(wd=O.ra)(a,b),xd=(a,b)=>(xd=O.sa)(a,b),dd=a=>(dd=O.ta)(a),ld=(a,b,c,d,e)=>(ld=O.ua)(a,b,c,d,e),md=(a,b,c)=>(md=O.va)(a,b,c),nd=(a,b)=>(nd=O.wa)(a,b),vd=(a,b,c)=>(vd=O.xa)(a,b,c),qd=(a,b)=>(qd=O.ya)(a,b),rd=(a,b)=>(rd=O.za)(a,b),Bd=(a,b)=>(Bd=O.Aa)(a,b),Cd=a=>(Cd=O.Ba)(a),Uc=a=>(Uc=O.Ca)(a),yd=a=>(yd=O.Da)(a),zd=a=>(zd=O.Ea)(a),Ad=
a=>(Ad=O.Fa)(a),$c=()=>($c=O.Ga)(),Xc=()=>(Xc=O.Ha)(),Zc=(a,b,c)=>(Zc=O.Ia)(a,b,c);g.dynCall_ii=(a,b)=>(g.dynCall_ii=O.Ja)(a,b);var dynCall_vi=g.dynCall_vi=(a,b)=>(dynCall_vi=g.dynCall_vi=O.Ka)(a,b);g.dynCall_iiii=(a,b,c,d)=>(g.dynCall_iiii=O.La)(a,b,c,d);var dynCall_iii=g.dynCall_iii=(a,b,c)=>(dynCall_iii=g.dynCall_iii=O.Ma)(a,b,c);g.dynCall_iiiii=(a,b,c,d,e)=>(g.dynCall_iiiii=O.Na)(a,b,c,d,e);
var dynCall_v=g.dynCall_v=a=>(dynCall_v=g.dynCall_v=O.Oa)(a),dynCall_vii=g.dynCall_vii=(a,b,c)=>(dynCall_vii=g.dynCall_vii=O.Pa)(a,b,c);g.dynCall_viii=(a,b,c,d)=>(g.dynCall_viii=O.Qa)(a,b,c,d);g.dynCall_iiiiii=(a,b,c,d,e,f)=>(g.dynCall_iiiiii=O.Ra)(a,b,c,d,e,f);g.dynCall_viiii=(a,b,c,d,e)=>(g.dynCall_viiii=O.Sa)(a,b,c,d,e);g.dynCall_iidiiii=(a,b,c,d,e,f,k)=>(g.dynCall_iidiiii=O.Ta)(a,b,c,d,e,f,k);g.dynCall_jiji=(a,b,c,d)=>(g.dynCall_jiji=O.Ua)(a,b,c,d);
g.dynCall_viijii=(a,b,c,d,e,f)=>(g.dynCall_viijii=O.Va)(a,b,c,d,e,f);g.dynCall_iiiiiiiii=(a,b,c,d,e,f,k,l,q)=>(g.dynCall_iiiiiiiii=O.Wa)(a,b,c,d,e,f,k,l,q);g.dynCall_iiiiiii=(a,b,c,d,e,f,k)=>(g.dynCall_iiiiiii=O.Xa)(a,b,c,d,e,f,k);g.dynCall_iiiiij=(a,b,c,d,e,f)=>(g.dynCall_iiiiij=O.Ya)(a,b,c,d,e,f);g.dynCall_iiiiid=(a,b,c,d,e,f)=>(g.dynCall_iiiiid=O.Za)(a,b,c,d,e,f);g.dynCall_iiiiijj=(a,b,c,d,e,f,k)=>(g.dynCall_iiiiijj=O._a)(a,b,c,d,e,f,k);
g.dynCall_iiiiiiii=(a,b,c,d,e,f,k,l)=>(g.dynCall_iiiiiiii=O.$a)(a,b,c,d,e,f,k,l);g.dynCall_iiiiiijj=(a,b,c,d,e,f,k,l)=>(g.dynCall_iiiiiijj=O.ab)(a,b,c,d,e,f,k,l);g.dynCall_viiiiii=(a,b,c,d,e,f,k)=>(g.dynCall_viiiiii=O.bb)(a,b,c,d,e,f,k);g.dynCall_ji=(a,b)=>(g.dynCall_ji=O.cb)(a,b);g.dynCall_iiiij=(a,b,c,d,e)=>(g.dynCall_iiiij=O.db)(a,b,c,d,e);g.dynCall_iij=(a,b,c)=>(g.dynCall_iij=O.eb)(a,b,c);g.dynCall_viiiii=(a,b,c,d,e,f)=>(g.dynCall_viiiii=O.fb)(a,b,c,d,e,f);
var Pb=a=>(Pb=O.gb)(a),Lb=()=>(Lb=O.hb)(),Ob=a=>(Ob=O.ib)(a),Qb=()=>(Qb=O.jb)();g.addRunDependency=Ba;g.removeRunDependency=Ca;g.FS_createPath=X.jc;g.FS_createPreloadedFile=X.kc;g.FS=X;g.FS_createDataFile=X.ic;g.FS_unlink=X.Gc;var Id;Aa=function Jd(){Id||Kd();Id||(Aa=Jd)};
function Kd(){function a(){if(!Id&&(Id=!0,g.calledRun=!0,!u)){La(wa);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();xa.unshift(b)}La(xa)}}if(!(0<A)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ya();La(va);0<A||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Kd();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default Module;
